Thahir quick corrections
bitstechfest/BTF-WebD pull request #6
Opened 2024-04-24 21:24 UTC by AhmedThahir

- Removed labels for fields; Placeholder is sufficient
- Changed registration button from Technofest to School, Enginuity to University (people may not remember which is which)
- Compressed images; 3mb for an image on a website is ridiculous, guys come on.
- Made mobile number format clearer in the placeholder

2024-04-25 14:53 UTC, howdoiusekeyboard commented
Hii, thanks for the PR

1. I think we should remove the placeholder if its repetitive instead of the labels because someone who has filled in their inputs might get confused at the end when they want to make a quick cross check of their data before submitting. As for the placeholder either it be blank for provide a specific instruction to the label

2. We could put schools and University in brackets ; eg Technofest (School). That would be better because at the end we don't want to lose oppurtunities on branding technofest and Enginuity

3. Yes good move. Compressed images would help with load times

4. Accepted

5. LGTM

Note: Edits to title img have disaligned it, it looked better before. Please fix

2024-04-25 14:56 UTC, howdoiusekeyboard requested changes

2024-04-25 14:56 UTC, howdoiusekeyboard commented on src/components/Pages/AboutUs.js
> +        <p>Enginuity is for engineering students to showcase their skills.</p> <br />
Isn't Enginuity Techno-Manegorial?, so not just engineering students

2024-04-25 14:56 UTC, howdoiusekeyboard commented on src/components/Pages/AboutUs.js
> +        <p>Technofest is for the next generation of aspiring students to explore the world of engineering.</p> <br />
Are you sure speciating to just engineering?

2024-04-26 20:31 UTC, AhmedThahir commented on src/components/Pages/AboutUs.js
> +        <p>Enginuity is for engineering students to showcase their skills.</p> <br />
You're right.

2024-04-26 20:31 UTC, AhmedThahir commented on src/components/Pages/AboutUs.js
> +        <p>Technofest is for the next generation of aspiring students to explore the world of engineering.</p> <br />
Right again

2024-04-26 20:39 UTC, AhmedThahir commented
Mahn this vercel needs so much authentication just for preview. So irritating. I just want to see the preview. Is there an easier method?

2024-04-27 09:11 UTC, merged